# topic
robot_pose_with_covariance_topic: "/vins_estimator/body_pose_stamped"
robot_pose_cache_size: 200   # 机器人位姿缓存的大小
# frame
map_frame_id: "map"
robot_base_frame_id: "base_link"
track_point_frame_id: "/base_link"  # The elevation map is moved along with the robot following a track point. This is the id of the tf frame in which the track point is defined
