log4j.logger.ros.deeprobotics_local_height_map=INFO,rosout_a   
log4j.appender.rosout_a=org.apache.log4j.RollingFileAppender 
log4j.appender.rosout_a.Threshold=INFO     
log4j.appender.rosout_a.ImmediateFlush=false     
log4j.appender.rosout_a.Append=true
log4j.appender.rosout_a.MaxFileSize=1000KB
log4j.appender.rosout_a.MaxBackupIndex=2
log4j.appender.rosout_a.File=${HOME}/log/height_map.log   
log4j.appender.rosout_a.layout=org.apache.log4j.PatternLayout   
log4j.appender.rosout_a.layout.ConversionPattern = %-d{yyyy-MM-dd HH:mm:ss} [%p] %m%n  
