import type { LayerConfigMap } from '../types/LayerConfig';

export const DEFAULT_LAYER_CONFIGS: LayerConfigMap = {
  grid: {
    id: 'grid',
    name: '网格',
    topic: '/map',
    messageType: null,
    enabled: false,
  },
  occupancy_grid: {
    id: 'occupancy_grid',
    name: '栅格地图',
    topic: '/map',
    messageType: 'nav_msgs/OccupancyGrid',
    enabled: true,
    colorMode: 'map',
    height: 0,
  },
  local_costmap: {
    id: 'local_costmap',
    name: '局部代价地图',
    topic: '/local_costmap/costmap',
    messageType: 'nav_msgs/OccupancyGrid',
    enabled: true,
    colorMode: 'costmap',
    alpha: 0.7,
    height: 0.02,
  },
  global_costmap: {
    id: 'global_costmap',
    name: '全局代价地图',
    topic: '/global_costmap/costmap',
    messageType: 'nav_msgs/OccupancyGrid',
    enabled: true,
    colorMode: 'costmap',
    alpha: 0.3,
    height: 0.01,
  },
  laser_scan: {
    id: 'laser_scan',
    name: '激光雷达',
    topic: '/scan',
    messageType: 'sensor_msgs/LaserScan',
    enabled: true,
    targetFrame: 'map',
  },
  robot: {
    id: 'robot',
    name: '机器人位置',
    topic: null,
    messageType: null,
    enabled: true,
    baseFrame: 'base_link',
    mapFrame: 'map',
    followZoomFactor: 0.3, // 跟随机器人时的缩放倍数（越小越放大）
  },
  local_plan: {
    id: 'local_plan',
    name: '局部路径',
    topic: '/local_plan',
    messageType: 'nav_msgs/Path',
    enabled: true,
    color: 0x00ff00,
    lineWidth: 2,
  },
  plan: {
    id: 'plan',
    name: '全局路径',
    topic: '/plan',
    messageType: 'nav_msgs/Path',
    enabled: true,
    color: 0x0000ff,
    lineWidth: 2,
  },
  footprint: {
    id: 'footprint',
    name: 'Footprint',
    topic: '/local_costmap/published_footprint',
    messageType: 'geometry_msgs/PolygonStamped',
    enabled: true,
  },
  tf: {
    id: 'tf',
    name: 'TF坐标系',
    topic: null,
    messageType: null,
    enabled: true,
    showFrameNames: true,
  },
  topology: {
    id: 'topology',
    name: 'Topology地图',
    topic: '/map/topology',
    messageType: 'topology_msgs/TopologyMap',
    enabled: true,
    color: 0x2196f3,
    pointSize: 0.1,
  },
  cmd_vel: {
    id: 'cmd_vel',
    name: '遥控',
    topic: '/cmd_vel',
    messageType: 'geometry_msgs/Twist',
    enabled: true,
    linearXSpeed: 0.5,
    linearYSpeed: 0.5,
    angularZSpeed: 0.5,
  },
  teb_local_plan: {
    id: 'teb_local_plan',
    name: 'TEB局部路径',
    topic: '/move_base/TebLocalPlannerROS/local_plan',
    messageType: 'nav_msgs/Path',
    enabled: true,
    color: 0x00ff00,
    lineWidth: 2,
  },
  global_plan: {
    id: 'global_plan',
    name: '全局规划路径',
    topic: '/move_base/GlobalPlanner/plan',
    messageType: 'nav_msgs/Path',
    enabled: true,
    color: 0x0000ff,
    lineWidth: 3,
  },
  voxel_grid: {
    id: 'pointcloud2',
    name: '体素障碍物点云',
    topic: '/move_base/local_costmap/stvl_obstacle_layer/voxel_grid',
    messageType: 'sensor_msgs/PointCloud2',
    enabled: true,
    color: 0xff6600,
    pointSize: 0.05,
    targetFrame: 'map',
    maxPoints: 2000,
  },
  map_cloud: {
    id: 'pointcloud2',
    name: '建图点云(registered)',
    topic: '/cloud_registered',
    messageType: 'sensor_msgs/PointCloud2',
    enabled: true,
    color: 0x00ff88,
    pointSize: 0.025,
    targetFrame: 'camera_init',
    accumulate: true,
    maxPoints: 3000,
    maxTotalPoints: 5000000,
  },
  laser_map: {
    id: 'pointcloud2',
    name: '全局地图点云',
    topic: '/Laser_map',
    messageType: 'sensor_msgs/PointCloud2',
    enabled: true,
    color: 0xffffff,
    pointSize: 0.08,
    targetFrame: 'camera_init',
  },
  slam_path: {
    id: 'path',
    name: 'SLAM轨迹',
    topic: '/path',
    messageType: 'nav_msgs/Path',
    enabled: true,
    color: 0xff4444,
    lineWidth: 5,
    mapFrame: 'camera_init',
  },
  initialpose: {
    id: 'initialpose',
    name: '重定位',
    topic: '/initialpose',
    messageType: 'geometry_msgs/PoseWithCovarianceStamped',
    enabled: true,
    baseFrame: 'base_link',
    mapFrame: 'map',
  },
};

