#controller_joint_names: ['', 'LF_Joint', 'LF_Joint_1', 'LF_Joint_2', 'LB_Joint', 'LB_Joint_1', 'LB_Joint_2', 'RF_Joint', 'RF_Joint_1', 'RF_Joint_2', 'RB_Joint', 'RB_Joint_1', 'RB_Joint_2', ]

controller_joint_names: ['',FL_HipX, FL_HipY, FL_Knee, FR_HipX, FR_HipY, FR_Knee, HL_HipX, HL_HipY, HL_Knee,
  HR_HipX, HR_HipY, HR_Knee,]

